//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarReservation.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarReservation.Web.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to search.
        /// </summary>
        public static string Book_Back {
            get {
                return ResourceManager.GetString("Book_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book_BookButton {
            get {
                return ResourceManager.GetString("Book_BookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Book_Car {
            get {
                return ResourceManager.GetString("Book_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Book_City {
            get {
                return ResourceManager.GetString("Book_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking confirmed.
        /// </summary>
        public static string Book_Confirmed {
            get {
                return ResourceManager.GetString("Book_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        public static string Book_EndDate {
            get {
                return ResourceManager.GetString("Book_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate.
        /// </summary>
        public static string Book_LicencePlate {
            get {
                return ResourceManager.GetString("Book_LicencePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm booking.
        /// </summary>
        public static string Book_New_Title {
            get {
                return ResourceManager.GetString("Book_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string Book_Price {
            get {
                return ResourceManager.GetString("Book_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per day.
        /// </summary>
        public static string Book_PricePerDay {
            get {
                return ResourceManager.GetString("Book_PricePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Book_SearchButton {
            get {
                return ResourceManager.GetString("Book_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Book_StartDate {
            get {
                return ResourceManager.GetString("Book_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a car.
        /// </summary>
        public static string Book_Title {
            get {
                return ResourceManager.GetString("Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete booking.
        /// </summary>
        public static string Book_UnableToComplete {
            get {
                return ResourceManager.GetString("Book_UnableToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking completed successfully.
        /// </summary>
        public static string Booking_Successful {
            get {
                return ResourceManager.GetString("Booking_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking dates.
        /// </summary>
        public static string Column_Dates {
            get {
                return ResourceManager.GetString("Column_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bookings.
        /// </summary>
        public static string History_Title {
            get {
                return ResourceManager.GetString("History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking details.
        /// </summary>
        public static string HistoryDetail_Title {
            get {
                return ResourceManager.GetString("HistoryDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking not found.
        /// </summary>
        public static string HistoryDetails_NotFound {
            get {
                return ResourceManager.GetString("HistoryDetails_NotFound", resourceCulture);
            }
        }
    }
}
